"""
Find the caption that belongs to an image inside an uploaded document.

A transcription of a drawing is far more useful when it is anchored to what
the document called that drawing. "Figure 12: Subfloor ventilation detail"
tells a reader -- and the compliance engine -- which requirement the drawing
is evidence for; without it, a description is a floating block of text about
some vents.

Two independent problems, because the containers are nothing alike:

  * **DOCX** has document order. The caption is a paragraph sitting next to
    the image, and Word usually styles it `Caption`. Alt text on the drawing
    itself (`wp:docPr/@descr`) is a second, often better source, because the
    author wrote it to describe that specific image.

  * **PDF** has no document order, only coordinates. The caption is whatever
    text sits closest underneath the image's bounding box (occasionally
    above), horizontally overlapping it.

Both are heuristics and both can miss. A wrong caption is worse than none --
it would attribute a drawing to the wrong requirement -- so each source is
scored and anything weak is dropped rather than guessed at.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# Caption openers seen in construction documents: NCC/ABCB figures, drawing
# registers, and the defaults Word and LaTeX produce.
CAPTION_PATTERN = re.compile(
    r"""^\s*
    (?P<kind>figure|fig\.?|table|diagram|drawing|detail|photo|image|plate|sketch|appendix)
    \s*
    # "12", "3.2", "10.2.15a", drawing-register forms like "A-101" / "SK.02",
    # and the NCC's clause-style ids: "H1D4a", "A6G3a". The lookahead keeps
    # this from swallowing an ordinary word -- a figure number has a digit in
    # it somewhere.
    (?P<number>(?=[A-Za-z0-9.\-]*\d)[A-Za-z0-9]+(?:[.\-][A-Za-z0-9]+)*)?
    # NCC figures are routinely qualified: "Figure H1D4a (explanatory): ...".
    (?:\s*\((?P<qualifier>[^)]{0,40})\))?
    \s*
    (?P<sep>[:.–—-]\s*)?
    (?P<title>.*)$
    """,
    re.IGNORECASE | re.VERBOSE,
)

# A caption is a label, not a paragraph of body text. Anything longer is
# almost certainly the prose around the image rather than its caption.
MAX_CAPTION_CHARS = 300

# Word's built-in caption styles, plus the names teams commonly clone.
CAPTION_STYLE_NAMES = {"caption", "figurecaption", "tablecaption", "imagecaption"}


@dataclass
class Caption:
    """A caption candidate, with where it came from and how much to trust it."""

    text: str
    source: str  # "alt-text" | "caption-style" | "caption-pattern" | "nearby-text"
    confidence: float  # 0.0-1.0; see SOURCE_CONFIDENCE

    def __bool__(self) -> bool:
        return bool(self.text)


# How much each discovery route is worth. Alt text and an explicit Caption
# style are authored deliberately; a regex match on nearby text is a guess,
# and bare proximity is the weakest signal we accept at all.
SOURCE_CONFIDENCE = {
    "alt-text": 0.95,
    "caption-style": 0.9,
    "caption-pattern": 0.75,
    "nearby-text": 0.4,
}

# Below this, a candidate is dropped rather than attached to the image.
MIN_CONFIDENCE = 0.4


def looks_like_caption(text: str) -> bool:
    """True if `text` opens the way a figure caption does."""
    if not text or len(text) > MAX_CAPTION_CHARS:
        return False
    match = CAPTION_PATTERN.match(text.strip())
    if not match:
        return False
    # "Figure" alone is a caption; so is "Figure 3.2 - Wall junction". But a
    # sentence merely starting with the word ("Figures are indicative only")
    # is not, so require either a number or a separator before any title.
    return bool(match.group("number") or match.group("sep") or not match.group("title"))


def clean(text: str) -> str:
    """Collapse whitespace and trim a caption to one tidy line."""
    return re.sub(r"\s+", " ", (text or "").strip())


def best_caption(candidates: list[Caption]) -> Caption | None:
    """Pick the most trustworthy candidate, or None if none clears the floor."""
    usable = [c for c in candidates if c.text and c.confidence >= MIN_CONFIDENCE]
    if not usable:
        return None
    return max(usable, key=lambda c: c.confidence)


def from_alt_text(alt: str | None, title: str | None = None) -> Caption | None:
    """Caption from a DOCX drawing's own alt text (`wp:docPr/@descr` or `@name`).

    Word puts an autogenerated placeholder in `@name` ("Picture 3", "image1.png"),
    so those are rejected -- they name the shape, they don't describe it.
    """
    for value in (alt, title):
        text = clean(value)
        if not text or len(text) > MAX_CAPTION_CHARS:
            continue
        if re.fullmatch(r"(picture|image|graphic|shape|chart|diagram)\s*\d*", text, re.IGNORECASE):
            continue
        if re.fullmatch(r"\S+\.(png|jpe?g|gif|bmp|tiff?|emf|wmf|svg)", text, re.IGNORECASE):
            continue
        return Caption(text=text, source="alt-text", confidence=SOURCE_CONFIDENCE["alt-text"])
    return None


def from_paragraph(text: str, style: str | None = None) -> Caption | None:
    """Caption from a DOCX paragraph near the image.

    An explicit `Caption` style is trusted on its own; any other paragraph has
    to look like a caption to qualify.
    """
    text = clean(text)
    if not text or len(text) > MAX_CAPTION_CHARS:
        return None

    normalised_style = re.sub(r"[^a-z]", "", (style or "").lower())
    if normalised_style in CAPTION_STYLE_NAMES:
        return Caption(text=text, source="caption-style", confidence=SOURCE_CONFIDENCE["caption-style"])

    if looks_like_caption(text):
        return Caption(text=text, source="caption-pattern", confidence=SOURCE_CONFIDENCE["caption-pattern"])

    return None


def from_nearby_text(text: str, distance: float, below: bool) -> Caption | None:
    """Caption from a PDF text block near an image's bounding box.

    `distance` is the gap in points between the image edge and the block.
    Captions sit directly under a figure far more often than over it, so a
    block above has to look like a caption to count at all.
    """
    text = clean(text)
    if not text or len(text) > MAX_CAPTION_CHARS:
        return None

    patterned = looks_like_caption(text)
    if not below and not patterned:
        return None

    if patterned:
        # A caption-shaped line stays trustworthy a bit further away, since
        # some layouts leave a wide gutter under the figure.
        confidence = SOURCE_CONFIDENCE["caption-pattern"] if distance <= 120 else SOURCE_CONFIDENCE["nearby-text"]
    else:
        # Unpatterned text is only worth taking when it is snug under the image.
        if distance > 40:
            return None
        confidence = SOURCE_CONFIDENCE["nearby-text"]

    return Caption(text=text, source="nearby-text" if not patterned else "caption-pattern", confidence=confidence)
